#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'supervisor'
        hostname: ubuntu-vbox
        username: supervisor
        password: '$y$j9T$vX953AaCn1sMRRHJ8cc3G.$Xyz/DG/nJmF4S3b89TuTySi25ak3GDh8e4GMgQvwnF7'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - git
        - wget
        - net-tools
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

